Fix not found error when specify customized BLAS path using environment variable (#806)
Summary:
### Description
When build the python bindings with existing `blas` installation by setting the environment variable `CBLAS_ROOT_DIR` or `CBLASDIR`, it fails to find `blas` library.

#### Reproduction Steps
1. `cd flashlight/bindings/python`
2. `USE_CUDA=0 USE_MKL=0 CBLAS_ROOT_DIR="/path/to/openblas/install/path" KENLM_ROOT="/path/to/kenlm/install/path" python3 setup.py build`

#### Trace of the error
running build
running build_py
package init file 'flashlight/__init__.py' not found (or not a regular file)
creating build
creating build/lib.linux-x86_64-3.8
creating build/lib.linux-x86_64-3.8/flashlight
creating build/lib.linux-x86_64-3.8/flashlight/lib
copying flashlight/lib/__init__.py -> build/lib.linux-x86_64-3.8/flashlight/lib
package init file 'flashlight/lib/audio/__init__.py' not found (or not a regular file)
creating build/lib.linux-x86_64-3.8/flashlight/lib/audio
copying flashlight/lib/audio/feature.py -> build/lib.linux-x86_64-3.8/flashlight/lib/audio
package init file 'flashlight/lib/sequence/__init__.py' not found (or not a regular file)
creating build/lib.linux-x86_64-3.8/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion_torch.py -> build/lib.linux-x86_64-3.8/flashlight/lib/sequence
copying flashlight/lib/sequence/criterion.py -> build/lib.linux-x86_64-3.8/flashlight/lib/sequence
package init file 'flashlight/lib/text/__init__.py' not found (or not a regular file)
creating build/lib.linux-x86_64-3.8/flashlight/lib/text
copying flashlight/lib/text/dictionary.py -> build/lib.linux-x86_64-3.8/flashlight/lib/text
copying flashlight/lib/text/decoder.py -> build/lib.linux-x86_64-3.8/flashlight/lib/text
running build_ext
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC
-- Performing Test COMPILER_SUPPORTS_RDYNAMIC - Success
-- -rdynamic supported.
-- Could NOT find GTest (missing: GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) (Required is at least version "1.10.0")
-- googletest not found - will download and build from source
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- FL_BACKEND is not CUDA - forcing FL_LIBRARIES_USE_CUDA to OFF
libraries criterions are not implemented for non-CUDA backends
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
-- Checking for module 'cblas'
--   No package 'cblas' found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [Accelerate]
-- Checking for [vecLib]
-- Checking for [cblas - atlas]
-- Checking for [openblas]
-- Checking for [cblas]
-- Checking for [blas]
CMake Error at cmake/FindCBLAS.cmake:334 (MESSAGE):
  CBLAS library not found.  Please specify library location
Call Stack (most recent call first):
  flashlight/lib/audio/feature/CMakeLists.txt:11 (find_package)
  flashlight/lib/audio/CMakeLists.txt:18 (include)
  flashlight/lib/CMakeLists.txt:35 (include)
  CMakeLists.txt:125 (include)
  -- Configuring incomplete, errors occurred!
See also "/data/common/archive/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
See also "/data/common/archive/flashlight/bindings/python/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "setup.py", line 110, in <module>
    setup(
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 56, in run
    self.build_extensions(ext)
  File "setup.py", line 104, in build_extensions
    subprocess.check_call(
  File "/home/xxx/opt/anaconda3/envs/pt-fast/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/data/common/archive/flashlight', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/data/common/archive/flashlight/bindings/python/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/home/xxx/opt/anaconda3/envs/pt-fast/bin/python3', '-DFL_BUILD_STANDALONE=OFF', '-DBUILD_SHARED_LIBS=ON', '-DFL_BUILD_CORE=OFF', '-DFL_BUILD_ALL_LIBS=ON', '-DFL_BUILD_EXAMPLES=OFF', '-DFL_BACKEND=CPU', '-DFL_LIBRARIES_BUILD_FOR_PYTHON=ON', '-DFL_LIBRARIES_USE_CUDA=OFF', '-DFL_LIBRARIES_USE_KENLM=ON', '-DFL_LIBRARIES_USE_MKL=OFF', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.

### Platform
- OS: Ubuntu 18.04.5 LTS
- Python 3.8.10

### Fix
Correct `IF(ENV{CBLAS_ROOT_DIR})` statement in `cmake/FindCBLAS.cmake` according to [cmake documentation](https://cmake.org/cmake/help/latest/command/if.html#defined) of `if` command.

Pull Request resolved: https://github.com/flashlight/flashlight/pull/806

Reviewed By: benoitsteiner

Differential Revision: D33817236

Pulled By: jacobkahn

fbshipit-source-id: 97c2530eba5bc7ec7e278e32244d10730a46eb04