Fix ostream op overload link issue on macos (#993)
Summary:
See title — ordering of translation units on macos can sometimes make this break, like with homebrew:
```
Undefined symbols for architecture x86_64:
  "std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::operator<<<char, std::__1::char_traits<char>, std::__1::allocator<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      fl::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, fl::dtype const&) in Types.cpp.o
      fl::operator<<(std::__1::basic_ostream<char, std::__1::char_traits<char> >&, fl::DeviceType const&) in DeviceType.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libflashlight.0.3.2.dylib] Error 1
make[1]: *** [CMakeFiles/flashlight.dir/all] Error 2
make: *** [all] Error 2
```

Compiler never complained because `ostream&` can exist as an incomplete type, but op overloading needed the symbol at link time.

Pull Request resolved: https://github.com/flashlight/flashlight/pull/993

Test Plan:
CI
+
```
brew tap bwasti/flashlight
brew install --build-from-source flashlight
```

Reviewed By: bwasti

Differential Revision: D38963907

Pulled By: jacobkahn

fbshipit-source-id: 1e668bb51411870bf13e0f7e6c2cb3a1be08f2c2